// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhHeghHW_2O8ijnfSZvP5m0ygNfcny6io',
    appId: '1:51450695913:web:5d74f7a6a9d982c490e078',
    messagingSenderId: '51450695913',
    projectId: 'inhomex-0203',
    authDomain: 'inhomex-0203.firebaseapp.com',
    storageBucket: 'inhomex-0203.firebasestorage.app',
    measurementId: 'G-WCZ5QZW6KW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVp-92U4FNPyAsi7QYx0mJzhg0E_PRdrw',
    appId: '1:51450695913:android:427b1a14f88f29da90e078',
    messagingSenderId: '51450695913',
    projectId: 'inhomex-0203',
    storageBucket: 'inhomex-0203.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIHId7EbJbIZUAif5VLG2XlqBpm1Wxq0I',
    appId: '1:51450695913:ios:0719ce3ccf3b061a90e078',
    messagingSenderId: '51450695913',
    projectId: 'inhomex-0203',
    storageBucket: 'inhomex-0203.firebasestorage.app',
    iosBundleId: 'com.example.inhomex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIHId7EbJbIZUAif5VLG2XlqBpm1Wxq0I',
    appId: '1:51450695913:ios:0719ce3ccf3b061a90e078',
    messagingSenderId: '51450695913',
    projectId: 'inhomex-0203',
    storageBucket: 'inhomex-0203.firebasestorage.app',
    iosBundleId: 'com.example.inhomex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhHeghHW_2O8ijnfSZvP5m0ygNfcny6io',
    appId: '1:51450695913:web:c6ea1d53c97143ef90e078',
    messagingSenderId: '51450695913',
    projectId: 'inhomex-0203',
    authDomain: 'inhomex-0203.firebaseapp.com',
    storageBucket: 'inhomex-0203.firebasestorage.app',
    measurementId: 'G-7C53SWHYKL',
  );
}
